
/**
 * An event generated by sometime of traffic condition
 * 
 * @author Matt
 * @version 1.0.0
 */
public class TrafficEvent extends CarPoolEvent {
	
	public TrafficEvent(int delay)
	{
		setTimeDelay(delay);
	}
}
