
/**
 * An event generated by sometime of traffic condition
 * 
 * @author Group 2
 * @version 1.0.0
 */
public class TrafficEvent extends CarPoolEvent {

	/**
	 * Creates a new traffic event with a delay of the given length
	 * @param delay The length of the delay caused by the traffic
	 */
	public TrafficEvent(int delay)
	{
		setTimeDelay(delay);
	}
}
